spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_review
    username: review
    password: review
    hikari:
      maximum-pool-size: 3
      minimum-idle: 3
      connection-timeout: 2000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    validateMigrationNaming: true
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
