spring:
  profiles:
    include: db, secret, oauth
---
spring:
  config:
    activate:
      on-profile: local, dev
  security:
    debug: true
  session:
    store-type: redis
    redis:
      namespace: aireview:session
    timeout: 3600
  data:
    redis:
      host: redis
      port: 6379
server:
  tomcat:
    threads:
      max: 10
      min-spare: 10
    max-connections: 100
    accept-count: 10
    connection-timeout: 2000
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  environment: {SENTRY_ENVIRONMENT}
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/manage"
---
spring:
  config:
    activate:
      on-profile: prod
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
      exposure:
        include: "health"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    diskspace:
      enabled: false
  security:
    debug: false
  data:
    redis:
      host: redis
      port: 6379
  session:
    store-type: { REDIS_HOST }
    redis:
      namespace: aireview:session
    timeout: 3600
server:
  tomcat:
    threads:
      max: 10
      min-spare: 10
    max-connections: 100
    accept-count: 10
    connection-timeout: 2000
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
